//
//  LoginEmailAndSocialRouter.swift
//  WhiteLabelApp
//
//  Created by hb on 16/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol for Login Email Social routing
protocol LoginEmailAndSocialRoutingLogic {
    func redirectToHome()
    func navigateToSignup()
}

/// Protocol for Login Email Social data passing
protocol LoginEmailAndSocialDataPassing {
    var dataStore: LoginEmailAndSocialDataStore? { get set }
}

/// Class for Login Email Social router
class LoginEmailAndSocialRouter: NSObject, LoginEmailAndSocialRoutingLogic, LoginEmailAndSocialDataPassing {
    /// Viewcontroller instance
    weak var viewController: LoginEmailAndSocialViewController?
    /// Datastore instance
    var dataStore: LoginEmailAndSocialDataStore?
    
    /// Redirect to home
    func redirectToHome() {
        let storyboard = UIStoryboard(name: "TabBar", bundle: nil)
        if let tab = storyboard.instantiateInitialViewController(), tab is TabbarController {
            GlobalUtility.setRootViewController(viewController: tab)
        }
    }
    
    /// Navigate to sign up
    func navigateToSignup() {
        if let signUpVC = SignUpViewController.instance() {
            signUpVC.isSocialType = self.viewController?.socialLoginType ?? ""
            signUpVC.facbookUserData = self.viewController?.facebookDict ?? [String:AnyObject]()
            signUpVC.googleDict = self.viewController?.googleDict
            signUpVC.googleDict = self.viewController?.googleDict
            signUpVC.appleUserData = self.viewController?.appleDict ?? [String:AnyObject]()
            self.viewController?.navigationController?.pushViewController(signUpVC, animated: true)
        }
    }
    
}
