//
//  MyProfileModels.swift
//  WhiteLabelApp
//
//  Created by hb on 25/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// My Profile Request and Response
enum UserInstitutions {
    
    /// Reponse Class
    class ViewModel: WSResponseData {
        var institutionId: String?
        var institutionName: String?
        var accessToken: String?
        var publicToken: String?
        var isFirstTransctionDump: String?
        var addedAt: String?
        var status: String?
        var institutionLogo: String?
        var institutionUrl: String?
        var institutionPrimaryColor: String?
        
        enum CodingKeys: String, CodingKey {
            case institution_id
            case institution_name
            case access_token
            case public_token
            case is_first_transactions_dumped
            case added_at
            case status
            case institution_logo
            case institution_url
            case institution_primary_color
        }
        
        /// Init default method
        ///
        /// - Parameter decoder: Decoder
        /// - Throws: throws exception if found error
        required init(from decoder: Decoder) throws {
            try super.init(from: decoder)
            let values = try decoder.container(keyedBy: CodingKeys.self)
            institutionId = try values.decodeIfPresent(String.self, forKey: .institution_id)
            institutionName = try values.decodeIfPresent(String.self, forKey: .institution_name)
            accessToken = try values.decodeIfPresent(String.self, forKey: .access_token)
            publicToken = try values.decodeIfPresent(String.self, forKey: .public_token)
            isFirstTransctionDump = try values.decodeIfPresent(String.self, forKey: .is_first_transactions_dumped)
            addedAt = try values.decodeIfPresent(String.self, forKey: .added_at)
            status = try values.decodeIfPresent(String.self, forKey: .status)
            institutionLogo = try values.decodeIfPresent(String.self, forKey: .institution_logo)
            institutionUrl = try values.decodeIfPresent(String.self, forKey: .institution_url)
            institutionPrimaryColor = try values.decodeIfPresent(String.self, forKey: .institution_primary_color)
        }
        
        /// Default encode method
        ///
        /// - Parameter encoder: Encoder
        /// - Throws:throws exception if found error
        public override func encode(to encoder: Encoder) throws {
            try super.encode(to: encoder)
            var container = encoder.container(keyedBy: CodingKeys.self)
            try container.encode(institutionId, forKey: .institution_id)
            try container.encode(institutionName, forKey: .institution_name)
            try container.encode(accessToken, forKey: .access_token)
            try container.encode(publicToken, forKey: .public_token)
            try container.encode(isFirstTransctionDump, forKey: .is_first_transactions_dumped)
            try container.encode(addedAt, forKey: .added_at)
            try container.encode(status, forKey: .status)
            try container.encode(institutionLogo, forKey: .institution_logo)
            try container.encode(institutionUrl, forKey: .institution_url)
            try container.encode(institutionPrimaryColor, forKey: .institution_primary_color)
        }
    }
}

enum RemoveAccount {
    struct Request {
        var accountId: String
    }
}
