//
//  GenerateLogPresenter.swift
//  Tyst
//
//  Created by hb on 08/11/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol GenerateLogPresentationLogic {
    
}

class GenerateLogPresenter: GenerateLogPresentationLogic {
    weak var viewController: GenerateLogDisplayLogic?
    
}
