//
//  ExportRouter.swift
//  Tyst
//
//  Created by hb on 06/11/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExportRoutingLogic {
    
}

protocol ExportDataPassing {
    var dataStore: ExportDataStore? { get set }
}

class ExportRouter: NSObject, ExportRoutingLogic, ExportDataPassing {
    weak var viewController: ExportViewController?
    var dataStore: ExportDataStore?
    
}
