//
//  ExportInteractor.swift
//  Tyst
//
//  Created by hb on 06/11/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ExportBusinessLogic {
    func getLogs(loader: Bool)
    func generateLogs(request: CreateLogs.Request)
}

protocol ExportDataStore {
    
}

class ExportInteractor: ExportBusinessLogic, ExportDataStore {
    var presenter: ExportPresentationLogic?
    var worker: ExportWorker?
    
    func getLogs(loader: Bool) {
        worker = ExportWorker()
        worker?.getTransactionDetail(loader: loader, completionHandler: { (response, message, success) in
            self.presenter?.presentLogs(response: response, message: message ?? "", success: success ?? "")
        })
    }
    
    func generateLogs(request: CreateLogs.Request) {
        worker = ExportWorker()
        worker?.createLogs(request: request, completionHandler: { (message, success) in
            self.presenter?.presentCreateLogResponse(message: message ?? "", Success: success ?? "")
        })
    }
}
