//
//  CategoryListInteractor.swift
//  Tyst
//
//  Created by hb on 30/03/20.
//  Copyright (c) 2020 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoryListBusinessLogic {
    func getCategory()
}

protocol CategoryListDataStore {
    //var name: String { get set }
}

class CategoryListInteractor: CategoryListBusinessLogic, CategoryListDataStore {
    var presenter: CategoryListPresentationLogic?
    var worker: CategoryListWorker?
    //var name: String = ""
    
    // MARK: Do something
    
    func getCategory() {
        worker = CategoryListWorker()
        worker?.getCategoryResponse(completionHandler: { (response, message, success) in
            self.presenter?.presentCategoryList(response: response, message: message ?? "", success: success ?? "0")
        })
    }
}
