//
//  CategoryPresenter.swift
//  Tyst
//
//  Created by hb on 28/02/20.
//  Copyright (c) 2020 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol CategoryPresentationLogic {
    func presentCategory(response: [Category.ViewModel]?, message: String, success: String)
}

class CategoryPresenter: CategoryPresentationLogic {
    weak var viewController: CategoryDisplayLogic?
    
    // MARK: Do something
    
    func presentCategory(response: [Category.ViewModel]?, message: String, success: String) {
        viewController?.didReceivePresentCategory(response: response, message: message, success: success)
    }
}
