//
//  ForgotPasswordEmailPresenter.swift
//  WhiteLabelApp
//
//  Created by hb on 19/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol Forgot password email 
protocol ForgotPasswordEmailPresentationLogic {
    /// Present Forgot password Response
    ///
    /// - Parameters:
    ///   - message: API Message
    ///   - success: API Success
    func presentForgotPasswordResponse(message: String, success: String)
}

/// Class for forgot password email
class ForgotPasswordEmailPresenter: ForgotPasswordEmailPresentationLogic {
    /// View controller for forgot password
    weak var viewController: ForgotPasswordEmailDisplayLogic?
    
    /// Present Forgot password Response
    ///
    /// - Parameters:
    ///   - message: API Message
    ///   - success: API Success
    func presentForgotPasswordResponse(message: String, success: String) {
        self.viewController?.didReceiveForgotPasswordResponse(message: message, success: success)
    }
}
