//
//  LoginEmailRouter.swift
//  WhiteLabel
//
//  Created by hb on 09/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol for Login Email routing
protocol LoginEmailRoutingLogic {
    func redirectToHome()
}

/// Protocol for Login Email data passing
protocol LoginEmailDataPassing {
    var dataStore: LoginEmailDataStore? { get set }
}

/// Class for Login Email router
class LoginEmailRouter: NSObject, LoginEmailRoutingLogic, LoginEmailDataPassing {
    /// Viewcontroller instance
    weak var viewController: LoginEmailViewController?
    /// Datastore instance
    var dataStore: LoginEmailDataStore?
    
    /// Redirect to home
    func redirectToHome() {
        let storyboard = UIStoryboard(name: "TabBar", bundle: nil)
        if let tab = storyboard.instantiateInitialViewController(), tab is TabbarController {
            GlobalUtility.setRootViewController(viewController: tab)
        }
    }
}
