//
//  LoginEmailInteractor.swift
//  WhiteLabel
//
//  Created by hb on 09/09/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol for Login Social API
protocol LoginEmailBusinessLogic {
    /// Call Login with email API
    ///
    /// - Parameter request: Login email Social Request
    func loginWithEmail(request: LoginEmailModel.Request)
}

/// Protocol for Login Email Data Store
protocol LoginEmailDataStore {
    
}

/// Class for Login Email Interactor
class LoginEmailInteractor: LoginEmailBusinessLogic, LoginEmailDataStore {
    /// Presentor instance
    var presenter: LoginEmailPresentationLogic?
    /// Worker instance
    var worker: LoginEmailWorker?
    
    /// Call Login with email API
    ///
    /// - Parameter request: Login email Social Request
    func loginWithEmail(request: LoginEmailModel.Request) {
        worker = LoginEmailWorker()
        worker?.login(request: request, completionHandler: { (response, message, success) in
            self.presenter?.presentLoginResponse(response: response, message: message ?? "", success: success ?? "0")
        })
    }
}
