//
//  ReceiptsRouter.swift
//  Tyst
//
//  Created by hb on 06/11/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ReceiptsRoutingLogic {
    
}

protocol ReceiptsDataPassing {
    var dataStore: ReceiptsDataStore? { get set }
}

class ReceiptsRouter: NSObject, ReceiptsRoutingLogic, ReceiptsDataPassing {
    weak var viewController: ReceiptsViewController?
    var dataStore: ReceiptsDataStore?
}
