//
//  ChangePasswordInteractor.swift
//  Udecide
//
//  Created by hb on 15/04/19.
//  Copyright (c) 2019 hb. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

/// Protocol for change password API
protocol ChangePasswordBusinessLogic {
    /// Change password API
    ///
    /// - Parameter request: Change password request
    func changePassword(request: ChangePassword.Request)
}

/// Protocol Change Password datastore
protocol ChangePasswordDataStore {
    
}

/// Class for change password interactor
class ChangePasswordInteractor: ChangePasswordBusinessLogic, ChangePasswordDataStore {
    /// Presentor instance
    var presenter: ChangePasswordPresentationLogic?
    /// Worker instance
    var worker: ChangePasswordWorker?
    
    /// Change password API
    ///
    /// - Parameter request: Change password request
    func changePassword(request: ChangePassword.Request) {
        worker = ChangePasswordWorker()
        worker?.changePassword(request: request, completionHandler: { (message, success) in
            self.presenter?.presentChangePassword(message: message ?? "", success: success ?? "0")
        })
    }
}
